version: '3'
services:
  database:
    image: mongo:latest
    container_name: database
    ports:
      - '27017:27017'

  api:
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./
    env_file: .env
    depends_on:
      - 'database'
    # ports:
    #   - '9093:9093' # server port goes here

  nginx:
    depends_on:
      - api
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
    restart: always
