name: dev CI
on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  build:
    name: Build, test, and deploy
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: ['16.x']
        os: [ubuntu-latest]

    steps:
      - name: Checkout master
        uses: actions/checkout@master

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      - name: Run Test
        env:
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
        run: npm run test